#!/bin/bash
set -e
MON="eDP-1-1"
STEP=0.05        
MAX=1.00

CurrBright=$( xrandr --verbose --current | grep ^"$MON" -A5 | tail -n1 )
CurrBright="${CurrBright##* }"

MathBright=$CurrBright

if [[ "$1" == "Up" || "$1" == "+" ]]; then
	MathBright=$(echo "scale=3;$CurrBright+$STEP" | bc)
	if (( $(bc <<< "$MathBright > $MAX"))); then
		MathBright=$MAX
	fi
fi

if [[ "$1" == "Down" || "$1" == "-" ]]; then 
	MathBright=$(echo "scale=4;$CurrBright-$STEP" | bc)
	if (( $(bc <<< "$MathBright < $STEP"))); then
		MathBright=$STEP
	fi
fi

re='^[0-9]+([.][0-9]+)?$'
if [[ $1 =~ $re ]] ; then
	MathBright=$1
	if (( $(bc <<< "$MathBright < $STEP"))); then
		MathBright=$STEP
	fi
	if (( $(bc <<< "$MathBright > $MAX"))); then
		MathBright=$MAX
	fi
fi


xrandr --output "$MON" --brightness $MathBright

printf "Monitor $MON "
echo $( xrandr --verbose --current | grep ^"$MON" -A5 | tail -n1 )
